// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpzrfhrwfnaaqcsqrvch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwenJmaHJ3Zm5hYXFjc3FydmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTEyNjYsImV4cCI6MjA2OTA4NzI2Nn0.sNyOZNo6t5yDQ1MKEUgirgaIjwyfW0tqmD2xfbggbJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});